spring:
  application:
    name: sparta-onetoone
  datasource:
    url: jdbc:postgresql://localhost:5432/shop  # 데이터베이스 이름을 'shop'으로 변경
    username: ex
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret:
    key: ABCafasdfasdfsdfasdfasdfasdfasdfasdfasdfasdfadsf
  access-token-expiration-time: 3600000  # 1시간 (밀리초 단위)
  refresh-token-expiration-time: 604800000  # 7일 (밀리초 단위)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace